config/routes.rb
Rails.application.routes.draw do
  root 'persons#index'
  get  'persons' => 'persons#index'
  get 'list' => 'persons#list_all'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/person.rb
class Person < ApplicationRecord
   
   paginates_per 10

   def self.search(search)
      person = Person.where(first_name: search)
      if person.count == 0 #sem resultado
          return nil
      end
      return person
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    if !params[:search].nil? #if search is not nil
      result = Person.search(params[:search])
      if result
        @persons = result.page(params[:page])
          @persons
      else #se não achou nenhum resultado
        nil
      end
    else
      @persons = nil
    end
  end

  def list_all
    @persons = Person.page params[:page]
  end

  private
    def persons_params
      params.require(:person).permit(:search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/persons/index.html.erb
<h1>Persons</h1>
<h3><%= link_to 'Listar todas as pessoas', list_path %></h3>
<h4>Buscar por nome:</h4>
<%= form_with url: persons_path, method: :get do |form| %>
   <%= form.text_field :search, value: params[:search], placeholder: "Digite o primeiro nome" %>
   <%= form.submit "Buscar", name: nil %>
<% end %>

<% if @persons %>
   <ul>
      <% @persons.each do |person| %>
         <li><%= person.title %></li>
         <li><%= person.first_name %></li>
         <li><%= person.last_name %></li>
         <li><%= person.gender%></li>
         <li><%= person.email %></li>
         <li><%= image_tag person.picture %></li>
         <hr>
      <% end %>
   </ul>
   <div class="text-center">
      <%= paginate @persons %>
   </div>
<% else %>
   <h4>Nenhum resultado encontrado. </h4>
<% end %>

app/views/persons/list_all.html.erb
<h1>List All</h1>
<div>
  <%= link_to 'Busca', root_path %>
</div>

<ul>
  <% @persons.each do |person| %>
    <li><%= person.title %></li>
    <li><%= person.first_name %></li>
    <li><%= person.last_name %></li>
    <li><%= person.gender%></li>
    <li><%= person.email %></li>
    <li><%= image_tag person.picture %></li>
    <hr>
  <% end %>
</ul>

<div class="text-center">
  <%= paginate @persons %>
</div>